version: "3"
services:
  data: 
    command: npm run populate
		volumes:
      - /app/db
      - /app/node_modules
      
  appli:
    image: node:latest
    ports:
      - "8090:8082"
    depends_on:
      - data

