version: "3"
services:
  appli: 
    depends_on:
      - data
    image: node:latest
    command: npm start
    ports:
      - "8090:8082"
    restart: always
  
  data: 
    image: node:latest
    command: 
      - npm install
      - npm run populate
    restart: always
    volumes:
      - db_data:/app/db

volumes:
  db_data: {}

    
    
    

