version: "3"
services:
  appli: 
    depends_on:
      - data
    image: node:10.16.0-alpine
    command: npm run dev
    ports:
      - "8090:8082"
    restart: always
  
  data: 
    image: node:10.16.0-alpine
    build: .
    command: 
      - npm install
      - npm run populate
    volumes:
      - /app/db
      - /app/node_modules
    restart: always